const A=document.querySelector('#app');
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n)); const pick=a=>a[Math.floor(Math.random()*a.length)]; const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n); const compact=n=>new Intl.NumberFormat('it-IT',{notation:'compact',maximumFractionDigits:1}).format(n);
const ORIGINS=[
 {flag:'🇮🇹',country:'Italia',city:'Catanzaro',family:'Famiglia operaia',wealth:18400,opp:46,edu:52,rel:68,cost:48},
 {flag:'🇨🇭',country:'Svizzera',city:'Lugano',family:'Famiglia benestante',wealth:480000,opp:83,edu:74,rel:62,cost:88},
 {flag:'🇧🇷',country:'Brasile',city:'Recife',family:'Famiglia a basso reddito',wealth:3200,opp:31,edu:43,rel:78,cost:32},
 {flag:'🇩🇪',country:'Germania',city:'Amburgo',family:'Famiglia di ceto medio',wealth:76000,opp:67,edu:69,rel:64,cost:64},
 {flag:'🇯🇵',country:'Giappone',city:'Osaka',family:'Famiglia di ceto medio',wealth:92000,opp:71,edu:78,rel:57,cost:69},
 {flag:'🇺🇸',country:'USA',city:'Chicago',family:'Famiglia indebitata',wealth:-12000,opp:72,edu:61,rel:60,cost:76},
 {flag:'🇵🇹',country:'Portogallo',city:'Porto',family:'Famiglia modesta',wealth:26000,opp:55,edu:64,rel:73,cost:51},
 {flag:'🇮🇳',country:'India',city:'Pune',family:'Famiglia numerosa',wealth:7500,opp:42,edu:59,rel:82,cost:28}
];
const NAMES=['Andrea','Luca','Sofia','Giulia','Marco','Elena','Matteo','Noah','Maya','Leo','Nina','Sam'];
const EVENTS=[
 {min:5,max:7,tag:'INFANZIA',title:'Il primo giorno di scuola',text:'Non conosci nessuno. Durante la ricreazione vedi un bambino seduto da solo.',choices:[['Vai a parlargli',{rel:8,edu:1,karma:3},'Nasce una piccola amicizia.'],['Rimani per conto tuo',{rel:-2,edu:4,stress:2},'Passi il tempo osservando e leggendo.']]},
 {min:10,max:12,tag:'FAMIGLIA',title:'Una spesa imprevista',text:'A casa si rompe qualcosa di importante. I tuoi genitori discutono su come pagarlo.',choices:[['Offri i tuoi piccoli risparmi',{wealth:-150,rel:6,karma:4},'È poco, ma il gesto viene ricordato.'],['Tieni i soldi',{wealth:0,rel:-1},'Conservi ciò che hai.']]},
 {min:14,max:15,tag:'ECONOMIA',title:'Le entrate diminuiscono',text:'Uno dei tuoi genitori perde il lavoro. La tensione economica entra in casa.',choices:[['Cerchi un piccolo lavoro',{wealth:900,edu:-5,career:5,stress:4},'Impari presto il valore del denaro.'],['Ti concentri sulla scuola',{edu:10,rel:-2},'Scommetti sulla preparazione.'],['Provi a guadagnare online',{wealth:350,edu:4,career:8,risk:4},'Guadagni poco, impari molto.']]},
 {min:18,max:19,tag:'FUTURO',title:'La prima vera scelta',text:'La scuola è finita. Nessuna strada garantisce il risultato.',choices:[['Università',{wealth:-9000,edu:20,career:4,stress:3},'Investi tempo e denaro nella formazione.'],['Cerchi subito lavoro',{wealth:12000,edu:-2,career:14},'Entri presto nel mercato del lavoro.'],['Crei una piccola attività',{wealth:-4500,career:18,rep:5,risk:12},'Hai scelto una strada senza garanzie.']]},
 {min:22,max:24,tag:'RELAZIONI',title:'Una persona importante',text:'Conosci qualcuno con cui senti una connessione rara. Ma la tua vita è già piena di obiettivi.',choices:[['Le dai spazio',{rel:16,career:-3,stress:-5},'Una relazione diventa parte della tua storia.'],['Proteggi i tuoi obiettivi',{rel:-8,career:8,stress:3},'Vai avanti, ma qualcosa resta indietro.']]},
 {min:26,max:29,tag:'CARRIERA',title:'Un’occasione lontano da casa',text:'Ricevi un’offerta in un’altra città: più soldi, più responsabilità, meno certezze.',choices:[['Parti',{wealth:22000,career:16,rel:-9,stress:5},'La carriera accelera. Alcuni legami si raffreddano.'],['Rimani',{wealth:7000,career:6,rel:8,stress:-2},'Scegli continuità e legami.']]},
 {min:32,max:36,tag:'RISCHIO',title:'L’investimento',text:'Una persona di cui ti fidi propone di investire una parte importante dei tuoi risparmi.',choices:[['Investi il 40%',{gamble:true},'Il risultato non è sotto il tuo controllo.'],['Rifiuti',{rep:-1,stress:-1},'Proteggi ciò che possiedi.']]},
 {min:38,max:42,tag:'FAMIGLIA',title:'Una scelta di tempo',text:'Una persona cara ha bisogno di te proprio durante una fase decisiva del lavoro.',choices:[['Ci sei',{rel:18,career:-6,karma:6},'Perdi un’occasione, non un rapporto.'],['Resti concentrato sul lavoro',{career:12,rel:-15,rep:3},'La carriera sale. Il rapporto cambia.']]},
 {min:45,max:49,tag:'SALUTE',title:'Il corpo manda un segnale',text:'Da settimane sei più stanco del solito. Potrebbe non essere nulla.',choices:[['Fai dei controlli',{wealth:-1400,health:10,stress:-4},'Hai scelto di controllare in tempo.'],['Aspetti',{health:-14,stress:3},'Rimandi. Non sai ancora se sia stata una buona idea.']]},
 {min:52,max:56,tag:'DENARO',title:'Il salto di qualità',text:'Puoi usare gran parte del patrimonio per comprare un immobile o mantenere liquidità.',choices:[['Compri',{wealth:-65000,assets:1,rep:5},'Una parte della ricchezza cambia forma.'],['Mantieni liquidità',{wealth:6000,stress:-2},'Rimani più flessibile.']]},
 {min:60,max:64,tag:'TEMPO',title:'Quanto vale un anno?',text:'Ti offrono l’ultimo grande salto di carriera. Richiede quasi tutto il tuo tempo.',choices:[['Accetti',{wealth:45000,career:14,rel:-13,health:-6,stress:8},'Guadagni di più. Il prezzo non è solo economico.'],['Riduci il lavoro',{wealth:-7000,career:-4,rel:14,health:6,stress:-7},'Decidi di usare diversamente il tuo tempo.']]},
 {min:70,max:74,tag:'EREDITÀ',title:'Cosa lasci dietro di te?',text:'Hai abbastanza esperienza per aiutare qualcuno più giovane. Farlo richiede tempo e denaro.',choices:[['Fai da mentore',{wealth:-8000,rel:8,rep:16,karma:10},'Una parte di ciò che sai continuerà oltre te.'],['Pensi a te',{wealth:5000,rep:-3},'Conservi risorse e libertà.']]}
];
function fresh(){return {screen:'home',name:pick(NAMES),age:0,origin:null,wealth:0,edu:50,rel:60,rep:50,career:0,health:88,stress:12,karma:50,luck:Math.random(),assets:0,history:[],done:[],year:2026,born:2026,deathAge:null,score:0,occupation:'Nessuna',xp:0};}
let s=load()||fresh(); function save(){localStorage.setItem('onelife_save_v2',JSON.stringify(s))} function load(){try{return JSON.parse(localStorage.getItem('onelife_save_v2'))}catch(e){return null}}
function shell(content,nav=true){return `<main class="app"><header><button class="logo" onclick="go('home')">ONE <b>LIFE</b></button><span class="run">${s.origin?s.origin.flag+' '+s.age+' ANNI':'UNA SOLA RUN'}</span></header>${content}${nav&&s.origin?bottom():''}</main>`}
function bottom(){return `<nav><button onclick="go('life')" class="${s.screen==='life'?'on':''}">◉<small>Vita</small></button><button onclick="go('world')" class="${s.screen==='world'?'on':''}">⌾<small>Mondo</small></button><button onclick="go('career')" class="${s.screen==='career'?'on':''}">▣<small>Carriera</small></button><button onclick="go('profile')" class="${s.screen==='profile'?'on':''}">◇<small>Profilo</small></button></nav>`}
function home(){s.screen='home';A.innerHTML=shell(`<section class="hero"><span class="kicker">LIFE SIMULATOR</span><h1>NON SCEGLI<br><em>DOVE INIZIARE.</em></h1><p>Non conosci tutte le tue statistiche. Non sai quanto durerà. Non puoi ricaricare. Puoi solo decidere cosa fare della vita che ricevi.</p></section><section class="poster"><div class="globe"><i></i><i></i><i></i></div><div><b>IL MONDO NON È EQUO.</b><span>È proprio questo il gioco.</span></div></section>${s.origin?`<button class="primary" onclick="go('life')">CONTINUA LA TUA VITA <span>→</span></button><button class="ghost" onclick="confirmReset()">ABBANDONA QUESTA RUN</button>`:`<button class="primary pulse" onclick="birth()">NASCI <span>→</span></button>`}<p class="legal">Simulazione narrativa. Nessuna statistica rappresenta previsioni sulla vita reale.</p>`,false)}
function birth(){s=fresh();s.origin=pick(ORIGINS);s.wealth=s.origin.wealth;s.edu=s.origin.edu;s.rel=s.origin.rel;s.born=2026-Math.floor(Math.random()*5);s.year=s.born;s.screen='birth';save();A.innerHTML=shell(`<section class="birthScene"><div class="scan"></div><span class="kicker">GENERAZIONE COMPLETATA</span><div class="flag">${s.origin.flag}</div><h1>${s.origin.city}</h1><p>${s.origin.country} · ${s.family||s.origin.family}</p></section><section class="panel"><h3>${s.name} è nato.</h3><div class="stats2"><div><small>Famiglia</small><b>${s.origin.family}</b></div><div><small>Patrimonio familiare</small><b>${money(s.wealth)}</b></div><div><small>Opportunità</small><b>${'●'.repeat(Math.max(1,Math.round(s.origin.opp/20)))}<span>${'●'.repeat(5-Math.max(1,Math.round(s.origin.opp/20)))}</span></b></div><div><small>Salute reale</small><b>SCONOSCIUTA</b></div></div><div class="warning">Non hai scelto queste condizioni. Da ora in poi, molte cose dipenderanno da te. Non tutte.</div><button class="primary" onclick="startLife()">INIZIA LA TUA VITA →</button></section>`,false)}
function startLife(){s.age=5;s.year=s.born+5;save();nextEvent()}
function getEvent(){return EVENTS.find((e,i)=>!s.done.includes(i)&&s.age<=e.max)||null}
function nextEvent(){let e=getEvent();if(!e)return endLife();let idx=EVENTS.indexOf(e);s.age=Math.max(s.age,e.min+Math.floor(Math.random()*(e.max-e.min+1)));s.year=s.born+s.age;s.screen='life';save();A.innerHTML=shell(`${hud()}<section class="ageLine"><b>${s.age}</b><span>ANNI<br><small>${s.year}</small></span></section><section class="eventVisual ${e.tag.toLowerCase()}"><div class="avatar">${s.name[0]}</div><span>${e.tag}</span><div class="horizon"></div></section><section class="event"><span class="kicker">DECIDI</span><h2>${e.title}</h2><p>${e.text}</p>${e.choices.map((c,i)=>`<button class="choice" onclick="choose(${idx},${i})"><i>${String.fromCharCode(65+i)}</i><span>${c[0]}</span><b>›</b></button>`).join('')}</section>`)}
function hud(){return `<section class="hud"><div><small>€</small><b>${compact(s.wealth)}</b></div><div><small>STUDIO</small><b>${s.edu}</b></div><div><small>LEGAMI</small><b>${s.rel}</b></div><div><small>CARRIERA</small><b>${s.career}</b></div></section>`}
function apply(d){for(const k of ['wealth','edu','rel','rep','career','health','stress','karma','assets'])if(d[k])s[k]+=d[k]; if(d.gamble){let stake=Math.max(0,s.wealth*.4);if(Math.random()<.28+s.luck*.35){s.wealth+=stake*1.35;s.rep+=5;return 'L’investimento riesce. Il rischio questa volta ti premia.'}s.wealth-=stake;return 'L’investimento fallisce. Una parte importante dei risparmi scompare.'}s.edu=clamp(s.edu);s.rel=clamp(s.rel);s.rep=clamp(s.rep);s.career=clamp(s.career);s.health=clamp(s.health);s.stress=clamp(s.stress);return null}
function choose(ei,ci){let e=EVENTS[ei],c=e.choices[ci],special=apply(c[1]);s.done.push(ei);s.history.push({age:s.age,year:s.year,title:e.title,choice:c[0],tag:e.tag});s.xp+=10;s.age+=Math.max(1,Math.floor((e.max-e.min)/2)); if(s.career>65)s.occupation='Dirigente'; else if(s.career>40)s.occupation='Professionista'; else if(s.career>18)s.occupation='Lavoratore';save();A.innerHTML=shell(`${hud()}<section class="panel consequence"><span class="kicker">CONSEGUENZA</span><h2>${e.title}</h2><p>${special||c[2]}</p><div class="fog">Alcune conseguenze sono già visibili.<br><b>Altre stanno lavorando in silenzio.</b></div><button class="primary" onclick="nextEvent()">CONTINUA →</button></section>`)}
function life(){if(!s.origin)return home();nextEvent()}
function world(){s.screen='world';save();A.innerHTML=shell(`<section class="title"><span class="kicker">IL TUO MONDO</span><h1>${s.origin.city}</h1><p>${s.origin.flag} ${s.origin.country} · costo della vita ${s.origin.cost}/100</p></section><section class="map"><div class="mapgrid"></div><span class="pin">●<b>SEI QUI</b></span><span class="city c1">LAVORO</span><span class="city c2">STUDIO</span><span class="city c3">CASA</span></section><section class="panel"><h3>La mappa cresce con te.</h3><p class="muted">Nella versione online, città, aziende, immobili e opportunità diventeranno nodi condivisi tra i giocatori.</p><div class="locked">MULTIPLAYER WORLD <b>IN SVILUPPO</b></div></section>`)}
function career(){s.screen='career';save();let jobs=[['Lavoro stabile','Entrata sicura, crescita lenta',8,6000],['Specializzazione','Più studio, migliori opportunità',12,-2500],['Impresa','Rischio alto, crescita potenziale',18,-6000]];A.innerHTML=shell(`<section class="title"><span class="kicker">CARRIERA</span><h1>${s.occupation}</h1><p>Livello carriera ${s.career}/100</p></section><section class="progress"><i style="width:${s.career}%"></i></section><section class="panel"><h3>Prossima mossa</h3>${jobs.map((j,i)=>`<button class="job" onclick="job(${i})"><div><b>${j[0]}</b><small>${j[1]}</small></div><span>→</span></button>`).join('')}</section>`)}
function job(i){let opts=[[8,6000,0],[12,-2500,8],[18,-6000,3]][i];if(s.age<18){toast('Sei troppo giovane.');return}s.career=clamp(s.career+opts[0]);s.wealth+=opts[1];s.edu=clamp(s.edu+opts[2]);s.stress=clamp(s.stress+4);s.history.push({age:s.age,year:s.year,title:'Scelta di carriera',choice:['Lavoro stabile','Specializzazione','Impresa'][i],tag:'CARRIERA'});save();career()}
function profile(){s.screen='profile';save();A.innerHTML=shell(`<section class="profile"><div class="portrait">${s.name[0]}</div><div><span class="kicker">GIOCATORE</span><h1>${s.name}</h1><p>${s.age} anni · ${s.origin.city}</p></div></section><section class="panel"><div class="metric"><span>Patrimonio</span><b>${money(s.wealth)}</b></div><div class="metric"><span>Istruzione</span><b>${s.edu}/100</b></div><div class="metric"><span>Relazioni</span><b>${s.rel}/100</b></div><div class="metric"><span>Reputazione</span><b>${s.rep}/100</b></div><div class="metric"><span>Immobili</span><b>${s.assets}</b></div><div class="metric secret"><span>Salute reale</span><b>???</b></div><div class="metric secret"><span>Tempo rimanente</span><b>???</b></div></section><section class="panel"><span class="kicker">DIARIO</span>${s.history.length?s.history.slice().reverse().map(x=>`<div class="diary"><b>${x.age} anni</b><span>${x.title}</span><small>${x.choice}</small></div>`).join(''):'<p class="muted">La tua storia deve ancora cominciare.</p>'}</section>`)}
function endLife(){let healthFactor=(s.health-s.stress*.25-60)/4;let life=Math.round(clamp(72+healthFactor+(s.luck-.5)*18,48,101));s.deathAge=Math.max(s.age,life);s.age=s.deathAge;s.year=s.born+s.age;let wealthScore=clamp(50+Math.log10(Math.max(1,Math.abs(s.wealth)))*7+(s.wealth<0?-35:0));s.score=Math.round(clamp(s.edu*.17+s.rel*.2+s.rep*.17+s.career*.18+s.karma*.13+wealthScore*.15));s.screen='dead';save();A.innerHTML=shell(`<section class="death"><div class="deathIcon">×</div><span>PERSONAGGIO MORTO</span><h1>GAME OVER</h1><p>${s.name} · ${s.origin.city} · ${s.born}—${s.year}</p></section><section class="epitaph"><b>${s.age}</b><span>ANNI<br>VISSUTI</span></section><section class="panel"><div class="metric"><span>Patrimonio finale</span><b>${money(s.wealth)}</b></div><div class="metric"><span>Carriera</span><b>${s.career}/100</b></div><div class="metric"><span>Istruzione</span><b>${s.edu}/100</b></div><div class="metric"><span>Relazioni</span><b>${s.rel}/100</b></div></section><section class="score"><small>PUNTEGGIO VITA</small><b>${s.score}</b><p>Questa vita ha ottenuto un indice complessivo di <strong>${s.score}/100</strong>. Non esiste una vita perfetta.</p></section><section class="panel"><span class="kicker">LA TUA STORIA</span>${s.history.map(x=>`<div class="diary"><b>${x.age}</b><span>${x.title}</span><small>${x.choice}</small></div>`).join('')}</section><button class="primary" onclick="newRun()">NASCI DI NUOVO →</button><button class="ghost" onclick="go('home')">HOME</button>`,false)}
function newRun(){localStorage.removeItem('onelife_save_v2');s=fresh();birth()} function confirmReset(){if(confirm('Questa run verrà cancellata. Continuare?'))newRun()} function go(x){if(x==='home')home();else if(x==='life')life();else if(x==='world')world();else if(x==='career')career();else profile()} function toast(t){let d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
if(s.screen==='dead')endLife();else if(s.origin)go(s.screen==='birth'?'life':s.screen);else home();
