const c=document.getElementById('world'),ctx=c.getContext('2d'); const W=2400,H=1500;
const keys={}, player={x:280,y:1110,r:13,speed:3.2,inCar:false,money:320,energy:88,hunger:82,stress:18,social:65,reputation:50};
let minutes=450, day=0, frame=0, modalOpen=false, quest=0, partyChoice=null;
const memories=["07:30 — Ti sei svegliato. Oggi hai un esame importante."];
const buildings=[
{x:120,y:960,w:330,h:300,name:'CASA',type:'home',color:'#b98d68'},
{x:700,y:160,w:510,h:330,name:'LICEO NOVA',type:'school',color:'#b75e55'},
{x:1530,y:150,w:500,h:330,name:'CENTRO COMMERCIALE',type:'shop',color:'#597b73'},
{x:1540,y:930,w:480,h:310,name:'NEON CLUB',type:'club',color:'#705d88'},
{x:700,y:930,w:500,h:310,name:'CAFFÈ / MARKET',type:'market',color:'#8a704d'},
{x:115,y:160,w:360,h:330,name:'OFFICINA RIVA',type:'work',color:'#586575'},
];
const roads=[{x:0,y:570,w:2400,h:220},{x:520,y:0,w:150,h:1500},{x:1280,y:0,w:150,h:1500},{x:2100,y:0,w:180,h:1500}];
const npcs=[{x:850,y:700,name:'Marco',role:'Compagno di scuola',talk:0},{x:1110,y:700,name:'Sara',role:'Compagna di scuola',talk:0},{x:1720,y:700,name:'Luca',role:'Conoscente',talk:0},{x:1010,y:1340,name:'Elena',role:'Barista',talk:0}];
const car={x:470,y:1120,w:52,h:28};
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function near(a,b,d=75){return Math.hypot(a.x-b.x,a.y-b.y)<d}
function toast(t){let e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function remember(t){memories.unshift(t); memories.splice(8); renderSide()}
function timeStr(){let total=minutes%1440,h=Math.floor(total/60),m=Math.floor(total%60);return `${['LUN','MAR','MER','GIO','VEN','SAB','DOM'][day%7]} ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function renderSide(){document.getElementById('clock').textContent=timeStr();document.getElementById('money').textContent='€ '+Math.round(player.money);let qs=[['Vai a scuola','L’esame di storia inizia alle 09:00. Puoi andarci, saltarlo o lasciarti distrarre.'],['Parla con Marco','Marco sembra volerti dire qualcosa dopo le lezioni.'],['Decidi per stasera','Hai ricevuto un invito per una festa al Neon Club.'],['Vivi la tua giornata','Ora sei libero: lavora, compra qualcosa, socializza, guida o torna a casa.']];document.getElementById('objective').innerHTML=`<div class="objective-title">${qs[quest][0]}</div><div class="small">${qs[quest][1]}</div>`;document.getElementById('meters').innerHTML=[['Energia',player.energy],['Fame',player.hunger],['Socialità',player.social],['Stress',100-player.stress]].map(x=>`<div class="meter"><label><span>${x[0]}</span><span>${Math.round(x[1])}%</span></label><div class="bar"><b style="width:${clamp(x[1],0,100)}%"></b></div></div>`).join('');document.getElementById('memory').innerHTML=memories.map(x=>`<div>• ${x}</div>`).join('')}
function modal(title,text,choices){modalOpen=true;document.getElementById('modal').classList.remove('hidden');document.getElementById('modalContent').innerHTML=`<span class="tag">ONE LIFE • DECISIONE</span><h2>${title}</h2><p>${text}</p><div class="choices">${choices.map((x,i)=>`<button class="choice" data-i="${i}">${x.label}</button>`).join('')}</div>`;document.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>{let x=choices[+b.dataset.i];x.fn();closeModal()}))}
function closeModal(){modalOpen=false;document.getElementById('modal').classList.add('hidden');c.focus()}document.getElementById('close').onclick=closeModal;
function interact(){if(modalOpen)return; let b=buildings.find(b=>player.x>b.x-35&&player.x<b.x+b.w+35&&player.y>b.y-35&&player.y<b.y+b.h+35);let n=npcs.find(n=>near(player,n,55));if(n)return talk(n);if(b)return enter(b);toast('Non c’è nulla con cui interagire qui.')}
function talk(n){if(n.name==='Marco'&&quest===1){modal('Marco',`“Stasera fanno una festa al Neon. Vieni? Ci sarà anche gente dell’università. Potrebbe essere divertente.”`,[{label:'Ci sto. Ci vediamo lì.',fn:()=>{partyChoice='yes';player.social+=5;quest=2;remember(`${timeStr()} — Hai promesso a Marco che andrai alla festa.`)}},{label:'No, domani voglio studiare.',fn:()=>{partyChoice='no';player.reputation+=2;quest=2;remember(`${timeStr()} — Hai rifiutato la festa per concentrarti sul futuro.`)}},{label:'Forse. Deciderò più tardi.',fn:()=>{partyChoice='maybe';quest=2;remember(`${timeStr()} — Hai lasciato aperta la decisione sulla festa.`)}}]);return}modal(n.name,`${n.role}. “Ehi! Come va?”`,[{label:'Parla un po’',fn:()=>{player.social+=7;minutes+=15;player.energy-=2;remember(`${timeStr()} — Hai passato del tempo con ${n.name}.`) }},{label:'Chiedi se sa di opportunità di lavoro',fn:()=>{minutes+=5;player.reputation+=1;remember(`${timeStr()} — Hai chiesto a ${n.name} informazioni sul lavoro.`);toast('Una nuova possibilità potrebbe comparire più avanti.')}}])}
function enter(b){if(b.type==='school'){if(quest===0){let late=minutes>540;modal('Liceo Nova',late?'Sei arrivato tardi. Il professore ti guarda dalla porta.':'Sei arrivato in tempo. Tra poco comincia l’esame.',[{label:'Entra e sostieni l’esame',fn:()=>{minutes+=90;player.energy-=12;player.stress+=late?15:6;quest=1;remember(`${timeStr()} — Hai sostenuto l’esame${late?' arrivando tardi':''}. Il risultato arriverà in futuro.`)}},{label:'Salta l’esame e vai via',fn:()=>{quest=1;player.stress-=5;player.reputation-=5;remember(`${timeStr()} — Hai saltato un esame. Questa scelta resterà nel tuo percorso scolastico.`)}}]);}else toast('Le lezioni sono finite per oggi.');}
if(b.type==='market')modal('Caffè / Market','Puoi comprare qualcosa o fermarti. Il tempo continua a passare.',[{label:'Panino e bibita — €8',fn:()=>{if(player.money>=8){player.money-=8;player.hunger=100;minutes+=20;remember(`${timeStr()} — Hai mangiato al market.`)}}},{label:'Caffè — €2',fn:()=>{if(player.money>=2){player.money-=2;player.energy+=8;minutes+=10}}},{label:'Chiedi un turno di lavoro',fn:()=>{minutes+=10;remember(`${timeStr()} — Hai lasciato il tuo numero al Caffè. Potrebbero richiamarti.`);toast('Contatto salvato: Caffè Nova')}}]);
if(b.type==='work')modal('Officina Riva','Il proprietario cerca qualcuno per piccoli lavori dopo scuola.',[{label:'Lavora 2 ore — +€28',fn:()=>{minutes+=120;player.money+=28;player.energy-=20;player.hunger-=12;remember(`${timeStr()} — Hai lavorato due ore in officina. +€28.`)}},{label:'Chiedi di imparare il mestiere',fn:()=>{minutes+=45;player.energy-=5;player.reputation+=4;remember(`${timeStr()} — Hai iniziato a imparare meccanica. Questa competenza potrà crescere.`)}}]);
if(b.type==='home')modal('Casa','Qui puoi recuperare energie, studiare e parlare con la tua famiglia.',[{label:'Studia 1 ora',fn:()=>{minutes+=60;player.energy-=8;player.stress+=3;remember(`${timeStr()} — Hai studiato per un’ora.`)}},{label:'Cena con la famiglia',fn:()=>{minutes+=50;player.hunger=100;player.social+=5;remember(`${timeStr()} — Hai cenato con la tua famiglia.`)}},{label:'Dormi fino alle 07:30',fn:()=>{day++;minutes=(day*1440)+450;player.energy=100;player.hunger-=20;player.stress-=15;remember(`${timeStr()} — Inizia un nuovo giorno.`)}}]);
if(b.type==='shop')modal('Centro Commerciale','Negozi, tecnologia, abbigliamento e persone da incontrare.',[{label:'Compra vestiti — €45',fn:()=>{if(player.money>=45){player.money-=45;player.reputation+=3;minutes+=40;remember(`${timeStr()} — Hai comprato dei vestiti.`)}}},{label:'Gira tra i negozi',fn:()=>{minutes+=35;player.social+=2}},{label:'Cerca lavoro',fn:()=>{minutes+=20;remember(`${timeStr()} — Hai inviato una candidatura a un negozio del centro commerciale.`)}}]);
if(b.type==='club'){if(minutes%1440<1140){toast('Il Neon Club apre alle 19:00.');return}modal('Neon Club',partyChoice==='yes'?'Marco ti vede entrare e ti presenta a un ragazzo che sta avviando una startup.':'Musica, gente e nuove conoscenze. Nessuno ti obbligava a venire.',[{label:'Resta alla festa e socializza',fn:()=>{minutes+=150;player.social+=18;player.energy-=22;player.stress-=8;remember(`${timeStr()} — Alla festa hai conosciuto Davide. Sta creando una startup. Questo incontro è stato memorizzato.`);quest=3}},{label:'Bevi troppo e lasciati andare',fn:()=>{minutes+=180;player.social+=10;player.energy-=35;player.stress-=12;remember(`${timeStr()} — Hai esagerato alla festa. Domani potresti pagarne le conseguenze.`);quest=3}},{label:'Vai via presto',fn:()=>{minutes+=35;player.energy-=5;remember(`${timeStr()} — Sei passato alla festa, ma sei andato via presto.`);quest=3}}])}}
function carToggle(){if(player.inCar){player.inCar=false;car.x=player.x+25;car.y=player.y;toast('Sei sceso dall’auto.')}else if(near(player,car,70)){player.inCar=true;toast('Sei salito in auto. WASD per guidare.')}else toast('Devi essere vicino alla tua auto.')}
function update(){if(!modalOpen){let sp=player.inCar?7:player.speed,dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(dx||dy){let l=Math.hypot(dx,dy);player.x=clamp(player.x+dx/l*sp,20,W-20);player.y=clamp(player.y+dy/l*sp,20,H-20);if(player.inCar){car.x=player.x;car.y=player.y}if(frame%20===0){minutes+=.35;player.hunger-=.015;player.energy-=.008}}}frame++;if(frame%60===0)renderSide()}
function draw(){let vw=c.width,vh=c.height,camX=clamp(player.x-vw/2,0,W-vw),camY=clamp(player.y-vh/2,0,H-vh);ctx.fillStyle='#314137';ctx.fillRect(0,0,vw,vh);ctx.save();ctx.translate(-camX,-camY);ctx.fillStyle='#314137';ctx.fillRect(0,0,W,H);roads.forEach(r=>{ctx.fillStyle='#343940';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeStyle='#d9c46a88';ctx.setLineDash([28,28]);ctx.lineWidth=3;if(r.w>r.h){ctx.beginPath();ctx.moveTo(r.x,r.y+r.h/2);ctx.lineTo(r.x+r.w,r.y+r.h/2);ctx.stroke()}else{ctx.beginPath();ctx.moveTo(r.x+r.w/2,r.y);ctx.lineTo(r.x+r.w/2,r.y+r.h);ctx.stroke()}ctx.setLineDash([])});buildings.forEach(b=>{ctx.fillStyle=b.color;ctx.fillRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#0005';ctx.fillRect(b.x,b.y+b.h-42,b.w,42);ctx.fillStyle='#fff';ctx.font='700 18px system-ui';ctx.fillText(b.name,b.x+18,b.y+b.h-16);ctx.fillStyle='#d9e2e8';for(let x=b.x+25;x<b.x+b.w-20;x+=65){ctx.fillRect(x,b.y+35,35,45)}});for(let i=0;i<80;i++){let x=(i*191)%W,y=(i*337)%H;if(!roads.some(r=>x>r.x-20&&x<r.x+r.w+20&&y>r.y-20&&y<r.y+r.h+20)){ctx.fillStyle='#1e3428';ctx.beginPath();ctx.arc(x,y,14,0,Math.PI*2);ctx.fill()}}npcs.forEach(n=>{ctx.fillStyle='#e2b48e';ctx.beginPath();ctx.arc(n.x,n.y-10,9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#293a55';ctx.fillRect(n.x-8,n.y,n.x?16:16,23);ctx.fillStyle='#fff';ctx.font='11px system-ui';ctx.fillText(n.name,n.x-17,n.y-26)});if(!player.inCar){ctx.fillStyle='#e3b48f';ctx.beginPath();ctx.arc(player.x,player.y-10,9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111827';ctx.fillRect(player.x-9,player.y,18,25)}ctx.fillStyle='#aeb8c4';ctx.fillRect(car.x-car.w/2,car.y-car.h/2,car.w,car.h);ctx.fillStyle='#27313b';ctx.fillRect(car.x-12,car.y-10,24,13);ctx.restore();ctx.fillStyle='#fff';ctx.font='700 12px system-ui';ctx.fillText(player.inCar?'IN AUTO':'A PIEDI',18,25)}
function loop(){update();draw();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{keys[e.key]=true;if(e.key.toLowerCase()==='e')interact();if(e.key.toLowerCase()==='f')carToggle()});addEventListener('keyup',e=>keys[e.key]=false);[['up','ArrowUp'],['down','ArrowDown'],['left','ArrowLeft'],['right','ArrowRight']].forEach(([id,k])=>{let b=document.getElementById(id);b.addEventListener('pointerdown',()=>keys[k]=true);b.addEventListener('pointerup',()=>keys[k]=false);b.addEventListener('pointerleave',()=>keys[k]=false)});document.getElementById('interact').onclick=interact;document.getElementById('car').onclick=carToggle;
document.querySelectorAll('[data-phone]').forEach(b=>b.onclick=()=>{let t=b.dataset.phone;if(t==='messages')modal('Messaggi','MARCO • 08:02\n“Stasera festa al Neon. Vieni?”',[{label:'Chiudi',fn:()=>{document.getElementById('msgBadge').style.display='none'}}]);if(t==='map')modal('Luoghi','Casa • Liceo Nova • Officina Riva • Caffè / Market • Centro Commerciale • Neon Club',[{label:'Chiudi',fn:()=>{}}]);if(t==='bank')modal('Banca',`Saldo disponibile: €${Math.round(player.money)}. Le tue entrate, spese e debiti influenzeranno le opportunità future.`,[{label:'Chiudi',fn:()=>{}}]);if(t==='jobs')modal('Lavoro','Al momento non hai un contratto. Puoi chiedere un turno all’Officina Riva o cercare lavoro nei negozi.',[{label:'Chiudi',fn:()=>{}}])});renderSide();c.focus();loop();
